### ISSUE TITLE
Possiblity to not publish snapshots and releases to the same channel

### ISSUE THREAD

**Issue by ckipp01** [joan38/kafka-streams-circe#26]
Hello! Thanks for you great work on this. We use it at my work and it's great! One thing we've come across is that your releases and snapshots are all released to the same place. For example, using coursier complete I'd expect this to just find your releases:

```
❯ cs complete com.goyeau:kafka-streams-circe_2.12:
https://repo1.maven.org/maven2/com/goyeau/kafka-streams-circe_2.12/maven-metadata.xml
  100.0% [##########] 1.1 KiB (3.9 KiB / s)
cefd63a
e5e3f70
e38cf69
e196b06
ecb9a51
f791f4a
f55955b
fbee94b
0.1
0.2
0.3
0.4
0.5
0.6
0.6.1
0.6.2
07be8ac
059a7d8
64ac0bb
133ba4e
503cd6b
776ec7e
818e5d7
2269bfb
28232c9
```
However, it also finds your snapshots. If you use Scala Steward (like we do at work), then Steward will always send in prs to update to the latest, `28232c9`. Just from a pr alone with that as the new version, it's quite difficult to determine what version this is tied to, was it by accident sense it doesn't follow any type of semantic versioning scheme, etc. This often leads to people just ignoring the update. Would it be possible to utilize a snapshot repository instead of releasing these all to the same place?

**Comment by joan38** [comment]
Hi @ckipp01,
True! I'm going to fix that across my projects.
Thanks

**Comment by joan38** [comment]
I tagged `0.6.3` even if there is not much change to flush out the latest version on maven release.
