### ISSUE TITLE
Empty Jar

### ISSUE THREAD

**Issue by mrebiai** [joan38/kafka-streams-circe#9]
This jar seems to be empty (no classes, only META-INF) : com.goyeau:kafka-streams-circe_2.13:0.6.1

**Comment by joan38** [comment]
That was due to a misconfiguration when I switched from SBT to Mill.
This is fixed now but Sonatype seems to be doing a planed maintenance right now. I'll publish `0.6.2` onces they are back up and update here.
Thanks for reporting it!

**Comment by joan38** [comment]
`0.6.2` published

**Comment by mrebiai** [comment]
Thanks!
